Repository kuzzleio/sdk-dart, pull requests merged in 2021-02, with the labels that each got.

#61 Fix documentation
  doc/2/controllers/document/count/index.md
  doc/2/controllers/document/m-create/index.md
  doc/2/controllers/document/m-update/index.md
Labels: changelog:exclude

#62 Add HTTP Protocol
  .ci/doc/project/pubspec.yaml
  .ci/doc/templates/without-ctor.tpl.dart
  doc/2/protocols/http/constructor/index.md
  doc/2/protocols/http/constructor/snippets/constructor.dart
  doc/2/protocols/http/constructor/snippets/constructor.test.yml
  doc/2/protocols/http/index.md
  doc/2/protocols/http/introduction/index.md
  lib/src/kuzzle.dart
  lib/src/protocols/abstract.dart
  lib/src/protocols/http.dart
  lib/src/protocols/websocket.dart
  pubspec.lock
  pubspec.yaml
Labels: changelog:new-features

#64 Export HttpProtocol
  .ci/doc/templates/without-ctor.tpl.dart
  lib/kuzzle.dart
Labels: changelog:bug-fixes

#65 Release 2.2.1
  .ci/doc/templates/without-ctor.tpl.dart
  CHANGELOG.md
  lib/kuzzle.dart
  pubspec.yaml
Labels: release

#66 Handle http error
  lib/src/protocols/http.dart
Labels: changelog:bug-fixes

#67 Release 2.2.2
  CHANGELOG.md
  lib/src/protocols/http.dart
  pubspec.yaml
Labels: release

#68 Add an option to accept bad SSL certificate
  doc/2/protocols/http/constructor/index.md
  lib/src/protocols/http.dart
Labels: changelog:new-features

#69 Release 2.3.0
  CHANGELOG.md
  doc/2/protocols/http/constructor/index.md
  lib/src/protocols/http.dart
  pubspec.yaml
Labels: release
