Repository kuzzleio/sdk-dart, pull requests merged in 2021-04, with the labels that each got.

#79 Decode http response with utf8
  lib/src/protocols/http.dart
Labels: changelog:enhancements

#80 Release 2.4.1
  .ci/doc/project/pubspec.yaml
  lib/src/protocols/http.dart
  lib/src/protocols/http_client_browser.dart
  lib/src/protocols/http_client_io.dart
  lib/src/protocols/websocket.dart
  lib/src/protocols/websocket_browser.dart
  lib/src/protocols/websocket_io.dart
  pubspec.yaml
Labels: release

#84 Fix autoreconnect
  lib/src/kuzzle.dart
  lib/src/protocols/abstract.dart
  lib/src/protocols/websocket_browser.dart
  lib/src/protocols/websocket_io.dart
Labels: changelog:bug-fixes

#75 Print deprecation warning from Kuzzle
  doc/2/core-classes/kuzzle/constructor/index.md
  lib/src/kuzzle.dart
  lib/src/kuzzle/response.dart
  lib/src/utils/deprecation.dart
Labels: changelog:enhancements

#86 Release 2.4.2
  CHANGELOG.md
  lib/src/kuzzle.dart
  lib/src/protocols/abstract.dart
  lib/src/protocols/websocket_browser.dart
  lib/src/protocols/websocket_io.dart
  pubspec.lock
  pubspec.yaml
Labels: release

#87 [HOTFIX] Use different flag to know if we should reconnect or not
  .github/workflows/pull_request.workflow.yml
  .github/workflows/push_dev.workflow.yml
  .github/workflows/push_master.workflow.yml
  CHANGELOG.md
  lib/src/protocols/websocket_io.dart
  pubspec.lock
  pubspec.yaml
Labels: changelog:bug-fixes
